spring.application.name=configserver
# A standard port for Config Servers is 8888
server.port=8888
# Point this to the absolute path of your local Git repo
# Use file:/// for local paths. Note the forward slashes.


# Point to your public GitHub repository
spring.cloud.config.server.git.uri=https://github.com/Nitinkuma1/config-server-repo.git
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# Specify the default branch (usually 'main' or 'master')
spring.cloud.config.server.git.default-label=main